djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    # 디폴트 페이지를 설정하기 위한 코드 (여기서는 pybo의 views에 구현된 index 함수가 실행되어 게시판으로 이동됨)
    # 3-11장에서 views 파일을 각각의 역할에 따라 별도의 파일로 분리하였으므로 여기서도 url에 대한 수정 필요.
    path('', base_views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

# 3-11장에서 views.py를 각 게시글 종류에 따라 역할을 담당하는 여러개의 *_views.py 파일로 나눔에 따라 참조 위치도 바뀜.

app_name = 'pybo'

urlpatterns = [
    # views -> base_views : 기초
    path('', base_views.index, name='index'),  # URL 별칭-->index
    path('<int:question_id>/', base_views.detail, name='detail'),  # URL 별칭-->detail

    # views -> question_views : 질문 게시글 관련
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # views -> answer_views : 답변 게시글 관련
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),

    # views -> comment_views : 댓글 관련
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # views -> vote_views : 게시글 추천 관련
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


# Q&A 게시판 생성

# 질문 게시글에 필요한 내용
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='question_author')
    # 익명질문이 가능하도록 질문 작성자에 null이 들어갈 수 있도록 함.
    # voter와 author가 동일하게 User 모델을 참조하기 때문에 어떤 필드를 우선 참조할지 결정하라는 오류 뜸 --> author_question 옵션 지정으로 해결
    subject = models.CharField(max_length=200)  # 질문 제목
    content = models.TextField()  # 질문 내용
    create_date = models.DateTimeField()  # 게시글 작성 시각
    modify_date = models.DateTimeField(null=True, blank=True)  # 최종 수정 시각. 수정 안해서 null값을 가질 수 있으므로 이를 허용.
    voter = models.ManyToManyField(User, related_name='question_voter')  # 추천한 사람 필드 추가

    # 하나의 질문에 여러 사람이 추천할 수 있고, 여러 사람이 하나의 질문 추천할 수 있으므로 다대다 필드로 설정.

    def __str__(self):
        return self.subject


# 답변 게시글에 필요한 내용
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answer_author')  # 답변 작성자
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 답변을 달 질문 게시글 정보, 질문 게시글 삭제시 답변도 삭제.
    content = models.TextField()  # 답변 내용
    create_date = models.DateTimeField()  # 답변 게시글 작성 시각
    modify_date = models.DateTimeField(null=True, blank=True)  # 최종 수정 시각. 수정 안해서 null값을 가질 수 있으므로 이를 허용.
    voter = models.ManyToManyField(User, related_name='answer_voter')


# 댓글 기능 구현에 필요한 클래스
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 댓글 작성자
    content = models.TextField()  # 댓글 내용
    create_date = models.DateTimeField()  # 댓글 작성 시각
    modify_date = models.DateTimeField(null=True, blank=True)  # 수정 시각
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)  # 이 댓글이 달린 질문
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)  # 이 댓글이 달린 답변

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']  # 임의로 '질문 제목', '질문 내용' 썼더니 에러뜸.
        # # form.as_p 로 생성한 질문 양식에 부트스트랩 적용하는 코드
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }

        # subject, content를 다른 이름으로 보이기 위한 코드
        labels = {
            'subject': '제목',
            'content': '질문 내용',
        }


# 답변 작성에 대한 양식 생성 코드
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용',  # 내용 라벨을 한국어로 보이게 하기 위한 코드
        }


# 댓글 작성 양식 생성 코드
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글 내용'  # 내용 라벨을 한국어로 보이게 하기 위한 코드
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Question, Answer
from ..forms import AnswerForm


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """ pybo 답변 등록 """
    # question과 코드는 유사. 차이점이라면 답변의 경우 질문에 종속되는 부가적인 정보이므로 질문에 대한 정보 필요.
    question = get_object_or_404(Question, pk=question_id)  # 질문에 대한 정보 가져옴. 없을경우 처리불가(404 에러)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # 답변 작성자 정보 등록
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """ 답변 수정 """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '게시글 관리 권한이 없습니다.')  # request 빼먹어서 오류 뜸
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect(
                '{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    # else문 들여쓰기 착각으로 인해 20분동안 헤맴
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """ 답변 삭제 """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '게시글 관리 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """ pybo 목록 출력 """
    page = request.GET.get('page', '1')  # 페이지 번호. 최초 번호=1
    kw = request.GET.get('kw', '')  # 검색어, 디폴트 검색어=''
    sortingorder = request.GET.get('sortingorder', 'recent') # 정렬 기준. 디폴트=최신순

    # 정렬
    if sortingorder=='recommend': # 추천순
        question_list=Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif sortingorder=='popular': # 인기순
        question_list=Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else: # 최신순(recent)인 경우
        question_list=Question.objects.order_by('-create_date')
    # question_list = Question.objects.order_by('-create_date')  # 최근 작성일 순으로 게시글 정렬하기 위해 - 붙임
    # 위의 코드는 정렬 옵션이 생김에 따라 마지막 else문에 합병됨.

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목으로 검색
            Q(content__icontains=kw) |  # 내용으로 검색
            Q(author__username=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    # 게시판 페이징 처리
    paginator = Paginator(question_list, 10)  # 10개 단위로 페이지 나누기 위한 코드
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}  # 게시글들 목록이 담긴 리스트, #3-15 이후 page와 kw 추가
    # 검색 해본 결과 : 원래 게시글의 번호가 아니라 1번부터 다시 지정됨.
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """ pybo 내용 출력 """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Question, Answer, Comment
from ..forms import CommentForm


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """ 질문 게시글에 댓글 작성 """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # 임시저장 이 아닌 바로 저장
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect(
                '{}comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question_id), comment.id))
    else:
        form = CommentForm()  # 무슨 코드지?
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """ 질문 게시글에 달려있는 댓글 수정 """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect(
                '{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))

    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """ 질문 게시글의 댓글 삭제 """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """ 답변 게시글에 댓글 생성 """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect(
                '{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """ 답변 게시글에 달린 댓글 수정 """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect(
                '{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """ 답변 게시글에 달린 댓글 삭제 """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    """ pybo 질문 등록 """
    # 질문 등록의 경우 get인 경우 질문 작성 양식만 가져오고, post인 경우 데이터가 저장되어야 하므로 각각에 대한 처리.
    if request.method == 'POST':  # 웹 페이지 요청 방식이 post인 경우 화면에서 전달받은 데이터로 양식 값이 채워지도록 설정.
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장 아님
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:  # else로 걸러지는 대부분의 요청방식은 get일 것이고, 이 경우 입력값 없이 객체 생성.
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """ 게시글 수정 """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '게시글 관리 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)  # 기존에 저장된 제목, 내용이 반영된 작성 양식 불러오기 위해 instance 설정
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장 아님
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:  # else로 걸러지는 대부분의 요청방식은 get일 것이고, 이 경우 입력값 없이 객체 생성.
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """ 게시글 삭제 """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '게시글 관리 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """ 질문 게시글에 추천 기능 등록 """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """ 답변 게시글에 추천 기능 등록 """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 답변은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-3">
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="content">답변 내용</label>
                <textarea class="form-control" name="content" id="content"
                          rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장</button>
        </form>
    </div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 작성</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글 내용</label>
            <textarea class="form-control" name="content" id="content" rows="3">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <div class="container my-3">
        <!-- 추천 기능 관련 오류 메시지 있을 경우 출력 코드 시작 -->
        {% if messages %} {# 오류 메시지가 전달되었을 경우 각각을 출력 #}
            <div class="alert alert-danger my-3" role="alert">
                {% for message in messages %}
                    <strong>{{ message.tags }}</strong>
                    <ul>
                        <li>{{ message.message }}</li>
                    </ul>
                {% endfor %}
            </div>
        {% endif %}
        <!-- 추천 기능 관련 오류 메시지 있을 경우 출력 코드 끝 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="row my-3">
            <div class="col-1">
                <!-- 추천 기능 구현 시작 -->
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                    {{ question.voter.count }}
                </div>
                <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
                   class="recommend btn btn-sm btn-secondary btn-block my-1">{# 추천 버튼 누르는 이벤트 얻기 위한 클래스 지정 #}
                    추천
                </a>
            </div>
            <div class="col-11">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text">
                            {{ question.content|mark }} {# 질문 게시글 작성에 마크다운 문법 추가하기 위해 |mark 추가 #}
                        </div>
                        <div class="d-flex justify-content-end">
                            {% if question.modify_date %}
                                <div class="badge badge-light p-2 text-left mx-3">
                                    <div class="mb-2">수정 시각:</div>
                                    <div>{{ question.modify_date }}</div>
                                </div>
                            {% endif %}
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">작성자: {{ question.author.username }}</div>
                                <div>작성 시각: {{ question.create_date }}</div>
                            </div>
                        </div>
                        {% if request.user == question.author %}
                            <div class="my-3">
                                <a href="{% url 'pybo:question_modify' question.id %}"
                                   class="btn btn-sm btn-outline-secondary">수정</a>
                                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                   data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                            </div>
                        {% endif %}
                        <!-- 질문 댓글 코드 시작 -->
                        {% if question.comment_set.count > 0 %} <!-- 댓글이 1개 이상일 경우에만 화면에 보여주는 조건문 -->
                            <div class="mt-3">
                                {% for comment in question.comment_set.all %}
                                    <a name="{{ comment.id }}"/>
                                    <div class="comment py-2 text-muted">
                                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                                        <span>
                                            - {{ comment.author }}, {{ comment.create_date }}
                                            {% if comment.modify_date %}
                                                (수정: {{ comment.modify_date }})
                                            {% endif %}
                                        </span>
                                        {% if request.user == comment.author %}
                                            <a href="{% url 'pybo:comment_modify_question' comment.id %}"
                                               class="small">수정</a>,
                                            <a href="#" class="small delete"
                                               data-uri="{% url 'pybo:comment_delete_question' comment.id %}">
                                                삭제
                                            </a>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div>
                            <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글 추가
                                ..</small></a>
                        </div>
                        <!-- 질문 댓글 코드 끝 -->
                    </div>
                </div>
            </div>
        </div>
        <h5 class="border-bottom my-3 py-2">
            답변: {{ question.answer_set.count }} 개
        </h5>
        {% for answer in question.answer_set.all %}
            <a name="answer_{{ answer.id }}"></a>
            <div class="row my-3">
                <div class="col-1"> <!-- 게시글 추천 코드 영역 시작 -->
                    <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                        {{ answer.voter.count }}
                    </div>
                    <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
                       class="recommend btn btn-sm btn-secondary btn-block my-1">
                        {# ^^^ 추천버튼 눌림 이벤트 지정(질문 게시글과 동일 ^^^ #}
                        추천
                    </a>
                </div>
                <div class="col-11"> <!-- 지정하지 않을 경우 답변 게시글 폭이 반토막남. -->
                    <div class="card"> <!-- class 지정에서 my-3 제외함. (폭이 반토막 나는거 방지) -->
                        <div class="card-body">
                            <div class="card-text">
                                {{ answer.content|mark }} {# 답변 게시글 작성에 마크다운 문법 추가하기 위해 |mark 추가 #}
                            </div>
                            <div class="d-flex justify-content-end">
                                {% if answer.modify_date %}
                                    <div class="badge badge-light p-2 text-left mx-3">
                                        <div class="mb-2">수정 시각:</div>
                                        <div>{{ answer.modify_date }}</div>
                                    </div>
                                {% endif %}
                                <div class="badge badge-light p-2 text-left">
                                    <div class="mb-2">작성자: {{ answer.author.username }}</div>
                                    <div>작성 시각: {{ answer.create_date }}</div>

                                </div>
                            </div>
                            {% if request.user == answer.author %}
                                <div class="my-3">
                                    <a href="{% url 'pybo:answer_modify' answer.id %}"
                                       class="btn btn-sm btn-outline-secondary">수정</a>
                                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                       data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                                </div>
                            {% endif %}
                            <!-- 답변 댓글 기능 구현 코드 시작 -->
                            {% if answer.comment_set.count > 0 %}
                                <div class="mt-3">
                                    {% for comment in answer.comment_set.all %}
                                        <a name="comment_{{ comment.id }}"/>
                                        <div class="comment py-2 text-muted">
                                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                                            <!-- comment.content를 span 태그 안에 넣는 실수 때문에 댓글 안보였음-->
                                            <span>
                                        - {{ comment.author }}, {{ comment.create_date }}
                                                {% if comment.modify_date %}
                                                    (수정: {{ comment.modify_date }})
                                                {% endif %}
                                    </span>
                                            {% if request.user == comment.author %}
                                                <a href="{% url 'pybo:comment_modify_answer' comment.id %}"
                                                   class="small">수정</a>,
                                                <a href="#" class="small delete"
                                                   data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">
                                                    삭제
                                                </a>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id %}"
                           class="small"><small>댓글 추가..</small></a>
                    </div>
                    <!-- 답변 댓글 기능 구현 코드 끝 -->
                </div>
            </div> <!-- 닫는 태그 누락으로 인해 답변의 댓글 노출 안됐었음. -->
            </div>

        {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {#        답변이 공백일 때 경고 띄우는 코드 시작 #}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        {#        답변이 공백일 때 경고 띄우는 코드 종료 #}
        <div class="form-group">
                <textarea name="content" id="content"
                          {% if not user.is_authenticated %}disabled{% endif %}
                          class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".delete").on('click', function () {
                if (confirm("정말 삭제하시겠습니까?")) {
                    location.href = $(this).data('uri');
                }
            });
            $(".recommend").on('click', function () {
                if (confirm("정말로 추천하시겠습니까?")) { //확인 버튼 눌러야 실제로 추천 수행함.
                    location.href = $(this).data('uri');
                }
            });
        });
    </script>
{% endblock %}