common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    # 디폴트 페이지를 설정하기 위한 코드 (여기서는 pybo의 views에 구현된 index 함수가 실행되어 게시판으로 이동됨)
    # 3-11장에서 views 파일을 각각의 역할에 따라 별도의 파일로 분리하였으므로 여기서도 url에 대한 수정 필요.
    path('', base_views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

# 3-11장에서 views.py를 각 게시글 종류에 따라 역할을 담당하는 여러개의 *_views.py 파일로 나눔에 따라 참조 위치도 바뀜.

app_name = 'pybo'

urlpatterns = [
    # views -> base_views : 기초
    path('', base_views.index, name='index'),  # URL 별칭-->index
    path('<int:question_id>/', base_views.detail, name='detail'),  # URL 별칭-->detail

    # views -> question_views : 질문 게시글 관련
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # views -> answer_views : 답변 게시글 관련
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),

    # views -> comment_views : 댓글 관련
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # views -> vote_views : 게시글 추천 관련
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """ pybo 목록 출력 """
    page = request.GET.get('page', '1')  # 페이지 번호. 최초 번호=1
    kw = request.GET.get('kw', '')  # 검색어, 디폴트 검색어=''
    sortingorder = request.GET.get('sortingorder', 'recent') # 정렬 기준. 디폴트=최신순

    # 정렬
    if sortingorder=='recommend': # 추천순
        question_list=Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif sortingorder=='popular': # 인기순
        question_list=Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else: # 최신순(recent)인 경우
        question_list=Question.objects.order_by('-create_date')
    # question_list = Question.objects.order_by('-create_date')  # 최근 작성일 순으로 게시글 정렬하기 위해 - 붙임
    # 위의 코드는 정렬 옵션이 생김에 따라 마지막 else문에 합병됨.

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목으로 검색
            Q(content__icontains=kw) |  # 내용으로 검색
            Q(author__username=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    # 게시판 페이징 처리
    paginator = Paginator(question_list, 10)  # 10개 단위로 페이지 나누기 위한 코드
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}  # 게시글들 목록이 담긴 리스트, #3-15 이후 page와 kw 추가
    # 검색 해본 결과 : 원래 게시글의 번호가 아니라 1번부터 다시 지정됨.
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """ pybo 내용 출력 """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- 필수 meta 태그 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 부트스트랩 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>pybo 게시가</title>
</head>
<body>
<!-- 네비게이션 바 템플릿 파일 포함시키는 코드 -->
{% include 'navbar.html' %}
<!-- 기본 템플릿에 포함될 내용이 삽입되는 구간 시작 지점-->
{% block content %}
{% endblock %}
<!-- 기본 템플릿에 포함될 내용이 삽입되는 구간 끝 지점-->
<!-- jQuery JS 포함시키는 코드 -->
<script src="{% static 'jQuery-3.6.0.min.js' %}"></script>
<!-- 부트스트랩 JS 포함시키는 코드-->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 코드 영역 시작 -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 코드 영역 끝 -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드에 어떤 오류가 발생했는지 출력 (보통 값 미입력 또는 입력 형식 잘못됐을때) -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 필드 오류가 아닌 에러를 출력 (입력값에 관계 없이 생성된 오류) -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션 바 코드 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo 질문 답변 게시판</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                {{ user.username }}님, 환영합니다.
                <a class="nav-link" href="{% url 'common:logout' %}">
                    로그아웃
                </a>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>